/**
 * Email Notification Service
 * Sends email alerts for critical system issues
 */

import { logger, LogCategory } from '../logger';

interface EmailMessage {
  to: string[];
  subject: string;
  html: string;
  text: string;
}

interface EmailAlert {
  title: string;
  message: string;
  severity: string;
  timestamp: string;
  context?: Record<string, any>;
}

class EmailService {
  private static instance: EmailService;
  private isEnabled: boolean;
  private apiKey?: string;
  private fromEmail?: string;

  private constructor() {
    this.isEnabled = !!process.env.EMAIL_SERVICE_API_KEY;
    this.apiKey = process.env.EMAIL_SERVICE_API_KEY;
    this.fromEmail = process.env.FROM_EMAIL || 'alerts@tiltvault.com';
  }

  static getInstance(): EmailService {
    if (!EmailService.instance) {
      EmailService.instance = new EmailService();
    }
    return EmailService.instance;
  }

  private generateAlertEmail(alert: EmailAlert): EmailMessage {
    const severityColors = {
      critical: '#dc3545',
      high: '#fd7e14',
      medium: '#ffc107',
      low: '#28a745'
    };

    const color = severityColors[alert.severity as keyof typeof severityColors] || '#6c757d';

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TiltVault Alert: ${alert.title}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background-color: #f8f9fa; }
          .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
          .header h1 { margin: 0; font-size: 24px; font-weight: 600; }
          .header p { margin: 10px 0 0 0; opacity: 0.9; }
          .content { padding: 30px; }
          .alert-box { border-left: 4px solid ${color}; background: #f8f9fa; padding: 20px; margin: 20px 0; border-radius: 4px; }
          .alert-title { font-size: 18px; font-weight: 600; margin: 0 0 10px 0; color: #333; }
          .alert-message { color: #666; line-height: 1.5; margin: 0 0 15px 0; }
          .alert-meta { font-size: 12px; color: #999; }
          .severity { display: inline-block; padding: 4px 8px; background: ${color}; color: white; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; }
          .context { margin-top: 20px; }
          .context-item { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
          .context-item:last-child { border-bottom: none; }
          .context-label { font-weight: 600; color: #333; }
          .context-value { color: #666; font-family: monospace; }
          .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #666; font-size: 14px; }
          .footer a { color: #667eea; text-decoration: none; }
          .timestamp { color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚨 TiltVault Alert</h1>
            <p>Critical system notification requiring attention</p>
          </div>
          
          <div class="content">
            <div class="alert-box">
              <div class="alert-title">${alert.title}</div>
              <div class="alert-message">${alert.message}</div>
              <div class="alert-meta">
                <span class="severity">${alert.severity}</span>
                <span class="timestamp">${new Date(alert.timestamp).toLocaleString()}</span>
              </div>
            </div>

            ${alert.context ? `
            <div class="context">
              <h3 style="margin: 0 0 15px 0; color: #333; font-size: 16px;">Context Information</h3>
              ${Object.entries(alert.context).map(([key, value]) => `
                <div class="context-item">
                  <span class="context-label">${key}:</span>
                  <span class="context-value">${typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}</span>
                </div>
              `).join('')}
            </div>
            ` : ''}
          </div>

          <div class="footer">
            <p>This alert was generated by the TiltVault monitoring system.</p>
            <p>For immediate assistance, contact the engineering team.</p>
            <p><a href="https://tiltvault.com/monitoring">View Monitoring Dashboard</a></p>
          </div>
        </div>
      </body>
      </html>
    `;

    const text = `
TiltVault Alert: ${alert.title}

Severity: ${alert.severity.toUpperCase()}
Time: ${new Date(alert.timestamp).toLocaleString()}

${alert.message}

${alert.context ? '\nContext Information:\n' + Object.entries(alert.context).map(([key, value]) => `${key}: ${typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}`).join('\n') : ''}

---
This alert was generated by the TiltVault monitoring system.
For immediate assistance, contact the engineering team.
Monitoring Dashboard: https://tiltvault.com/monitoring
    `;

    return {
      to: [], // Will be set by caller
      subject: `🚨 TiltVault Alert: ${alert.title}`,
      html,
      text
    };
  }

  private async sendViaSendGrid(email: EmailMessage): Promise<void> {
    if (!this.apiKey) {
      throw new Error('SendGrid API key not configured');
    }

    const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        personalizations: [{
          to: email.to.map(email => ({ email })),
          subject: email.subject
        }],
        from: { email: this.fromEmail },
        content: [
          { type: 'text/plain', value: email.text },
          { type: 'text/html', value: email.html }
        ]
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`SendGrid API error: ${response.status} - ${error}`);
    }

    logger.info('Email sent via SendGrid', LogCategory.API, {
      recipients: email.to,
      subject: email.subject
    });
  }

  private async sendViaAWSSES(email: EmailMessage): Promise<void> {
    // AWS SES implementation would go here
    // For now, we'll log it
    logger.info('Email would be sent via AWS SES', LogCategory.API, {
      recipients: email.to,
      subject: email.subject
    });
  }

  private async sendViaSMTP(email: EmailMessage): Promise<void> {
    // SMTP implementation would go here
    // For now, we'll log it
    logger.info('Email would be sent via SMTP', LogCategory.API, {
      recipients: email.to,
      subject: email.subject
    });
  }

  public async sendAlert(alert: EmailAlert, recipients: string[]): Promise<void> {
    if (!this.isEnabled) {
      logger.warn('Email service disabled', LogCategory.API);
      return;
    }

    try {
      const email = this.generateAlertEmail(alert);
      email.to = recipients;

      // Try SendGrid first (most reliable for transactional emails)
      if (this.apiKey && this.apiKey.startsWith('SG.')) {
        await this.sendViaSendGrid(email);
        return;
      }

      // Fall back to other methods
      if (process.env.AWS_SES_REGION) {
        await this.sendViaAWSSES(email);
      } else if (process.env.SMTP_HOST) {
        await this.sendViaSMTP(email);
      } else {
        logger.warn('No email service configured', LogCategory.API);
      }

    } catch (error) {
      logger.error('Failed to send email alert', LogCategory.API, {
        error: error instanceof Error ? error.message : 'Unknown error',
        alertTitle: alert.title,
        recipients
      });
    }
  }

  public async testEmailConfiguration(recipients: string[]): Promise<boolean> {
    try {
      const testAlert: EmailAlert = {
        title: 'Email Configuration Test',
        message: 'This is a test email to verify the email notification system is working correctly.',
        severity: 'low',
        timestamp: new Date().toISOString(),
        context: {
          test: true,
          service: 'TiltVault Monitoring',
          environment: process.env.NODE_ENV || 'development'
        }
      };

      await this.sendAlert(testAlert, recipients);
      return true;
    } catch (error) {
      logger.error('Email configuration test failed', LogCategory.API, {
        error: error instanceof Error ? error.message : 'Unknown error'
      });
      return false;
    }
  }
}

export const emailService = EmailService.getInstance();
